apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: 4
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-karpenter-sample
  # Node 削除条件
  ttlSecondsAfterEmpty: 30
